/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
//        System.out.println(System.getProperty("user.dir"));
        String inputFilePathToImage = "/Users/jenner/codefellows/Java-401/bitmap-transformer/app/src/main/resources/baldy-8bit.bmp";
        String outputFilePathToFolder = "/Users/jenner/codefellows/Java-401/bitmap-transformer/app/src/main/transformedPictures";
        String transformName = "greyJohn";
        Bitmap imageOne = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformName);
        imageOne.transformGrey();
        imageOne.transformWidth(500);
        imageOne.transformShirtColor();
    }
}
