/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        String inputFilePathToImage = "/Users/jenner/codefellows/Java-401/bitmap-transformer/app/src/main/resources/baldy-8bit.bmp";
        String outputFilePathToFolder = "/Users/jenner/codefellows/Java-401/bitmap-transformer/app/src/main/transformedPictures";
        String transformGrey = "greyJohn";
        String transformOutline = "outlineJohn";
        String transformWidth = "widthJohn";
        Bitmap imageOne = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformGrey);
        Bitmap imageTwo = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformWidth);
        Bitmap imageThree = new Bitmap(inputFilePathToImage, outputFilePathToFolder, transformOutline);
        imageOne.transformGrey();
        imageTwo.transformWidth(500);
        imageThree.transformOutlineColor();
    }
}
